In [1]:
import numpy as np


In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [5]:
type(np.array(mylist))

numpy.ndarray

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
type(0)

int

In [10]:
type(0.)

float

In [12]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.random.seed(101)

In [15]:
arr= np.random.randint(0,100,10)

In [16]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40], dtype=int32)

In [17]:
arr2= np.random.randint(0,100,10)

In [18]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40], dtype=int32)

In [19]:
arr.max()

np.int32(95)

In [20]:
arr.argmax()

np.int64(0)

In [21]:
arr.min()

np.int32(9)

In [23]:
arr.argmin()

np.int64(7)

In [24]:
arr.mean()

np.float64(60.8)

In [27]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]], dtype=int32)

In [33]:
mat = np.arange(0,100).reshape(10,10)

In [34]:
mat.shape

(10, 10)

In [35]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [36]:
row = 0
col= 1


In [37]:
mat[row][col]

np.int64(1)

In [40]:
mat[:,1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [41]:
mat[2, :]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [43]:
mat[0:3,0:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [44]:
mynewmat = mat.copy()

In [45]:
mynewmat[0:3, 0:4] =0


In [46]:
mynewmat

array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])